---
title: "Import and QC of OTG Data"
author: Mike Ackerman
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{otg-import-qc}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, results = "hide"}
# knitr options
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = TRUE,
  comment = "#>"
)

```

```{r setup}
# load necessary libraries
library(DASH)

```

# Introduction

This vignette describes how to import and QC on-the-ground (OTG) habitat data collected using the DASH protocol and Survey123 data collection forms. All of the functionality described here is available as part of the `DASH` R package available [here](https://github.com/BiomarkABS/DASH).

# Data Import

# Initial QC

# Resolving Errors

# "Final" QC

# Data Wrangling and Export

#### END IMPORT AND QC VIGNETTE

<!-- *Holy Guacamole! That deserves a beer!* -->
